import { cn } from "@/lib/utils";

const statusMap: Record<string, { label: string; className: string }> = {
  Draft: { label: "Brouillon", className: "bg-muted text-muted-foreground" },
  QC_Pending: { label: "QC en attente", className: "bg-warning/10 text-warning" },
  Approval_Pending: { label: "Approbation", className: "bg-info/10 text-info" },
  Pending_Approval: { label: "Approbation", className: "bg-info/10 text-info" },
  Approved: { label: "Approuvé", className: "bg-success/10 text-success" },
  Rejected: { label: "Rejeté", className: "bg-destructive/10 text-destructive" },
  Credit_Hold: { label: "Crédit bloqué", className: "bg-destructive/10 text-destructive" },
  Picking: { label: "Picking", className: "bg-warning/10 text-warning" },
  Packed: { label: "Emballé", className: "bg-info/10 text-info" },
  Shipped: { label: "Expédié", className: "bg-info/10 text-info" },
  Partially_Delivered: { label: "Partiel", className: "bg-warning/10 text-warning" },
  Delivered: { label: "Livré", className: "bg-success/10 text-success" },
  Invoiced: { label: "Facturé", className: "bg-primary/10 text-primary" },
  Cancelled: { label: "Annulé", className: "bg-muted text-muted-foreground" },
  Planning: { label: "Planification", className: "bg-muted text-muted-foreground" },
  Loading: { label: "Chargement", className: "bg-warning/10 text-warning" },
  In_Transit: { label: "En transit", className: "bg-info/10 text-info" },
  Completed: { label: "Terminé", className: "bg-success/10 text-success" },
  Pending: { label: "En attente", className: "bg-muted text-muted-foreground" },
  Loaded: { label: "Chargé", className: "bg-warning/10 text-warning" },
  Partial: { label: "Partiel", className: "bg-warning/10 text-warning" },
  Failed: { label: "Échoué", className: "bg-destructive/10 text-destructive" },
  Returned: { label: "Retourné", className: "bg-destructive/10 text-destructive" },
  Sent: { label: "Envoyée", className: "bg-info/10 text-info" },
  Partially_Paid: { label: "Partiel", className: "bg-warning/10 text-warning" },
  Paid: { label: "Payée", className: "bg-success/10 text-success" },
  Overdue: { label: "En retard", className: "bg-destructive/10 text-destructive" },
  Disputed: { label: "Contestée", className: "bg-destructive/10 text-destructive" },
  Completed_payment: { label: "Complété", className: "bg-success/10 text-success" },
  Pending_payment: { label: "En attente", className: "bg-warning/10 text-warning" },
  Bounced: { label: "Rejeté", className: "bg-destructive/10 text-destructive" },
  Cancelled_payment: { label: "Annulé", className: "bg-muted text-muted-foreground" },
  Pending_QC: { label: "QC en attente", className: "bg-warning/10 text-warning" },
  Submitted: { label: "Soumis", className: "bg-info/10 text-info" },
  Processed: { label: "Traité", className: "bg-info/10 text-info" },
  Credited: { label: "Crédité", className: "bg-success/10 text-success" },
  Active: { label: "Actif", className: "bg-success/10 text-success" },
  Inactive: { label: "Inactif", className: "bg-muted text-muted-foreground" },
  Suspended: { label: "Suspendu", className: "bg-destructive/10 text-destructive" },
  Blocked: { label: "Bloqué", className: "bg-destructive/10 text-destructive" },
  Confirmed: { label: "Confirmée", className: "bg-success/10 text-success" },
  Partially_Received: { label: "Partiel reçu", className: "bg-warning/10 text-warning" },
  Received: { label: "Reçue", className: "bg-success/10 text-success" },
  Scheduled: { label: "Planifié", className: "bg-muted text-muted-foreground" },
  In_Progress: { label: "En cours", className: "bg-info/10 text-info" },
  Pending_Review: { label: "Revue", className: "bg-warning/10 text-warning" },
  Requires_Investigation: { label: "Enquête", className: "bg-destructive/10 text-destructive" },
  Damage: { label: "Dommage", className: "bg-destructive/10 text-destructive" },
  Expiry: { label: "Expiration", className: "bg-warning/10 text-warning" },
  Correction: { label: "Correction", className: "bg-info/10 text-info" },
  Theft: { label: "Vol", className: "bg-destructive/10 text-destructive" },
  Shrinkage: { label: "Perte", className: "bg-warning/10 text-warning" },
  Found: { label: "Trouvé", className: "bg-success/10 text-success" },
  Available: { label: "Disponible", className: "bg-success/10 text-success" },
  Full: { label: "Plein", className: "bg-destructive/10 text-destructive" },
  Reserved: { label: "Réservé", className: "bg-warning/10 text-warning" },
  Maintenance: { label: "Maintenance", className: "bg-muted text-muted-foreground" },
  Passed: { label: "Conforme", className: "bg-success/10 text-success" },
  Conditional: { label: "Conditionnel", className: "bg-warning/10 text-warning" },
  Critical: { label: "Critique", className: "bg-destructive/10 text-destructive" },
  High: { label: "Haute", className: "bg-warning/10 text-warning" },
  Medium: { label: "Moyenne", className: "bg-info/10 text-info" },
  Low: { label: "Faible", className: "bg-muted text-muted-foreground" },
  Customer: { label: "Client", className: "bg-info/10 text-info" },
  Vendor: { label: "Fournisseur", className: "bg-warning/10 text-warning" },
  // Yard & Dock
  Occupied: { label: "Occupé", className: "bg-warning/10 text-warning" },
  Inbound: { label: "Réception", className: "bg-info/10 text-info" },
  Outbound: { label: "Expédition", className: "bg-warning/10 text-warning" },
  Both: { label: "Les deux", className: "bg-muted text-muted-foreground" },
  Checked_In: { label: "Enregistré", className: "bg-info/10 text-info" },
  Docked: { label: "Au quai", className: "bg-info/10 text-info" },
  Unloading: { label: "Déchargement", className: "bg-warning/10 text-warning" },
  Checked_Out: { label: "Sorti", className: "bg-success/10 text-success" },
  Return: { label: "Retour", className: "bg-destructive/10 text-destructive" },
  "Entrée": { label: "Entrée", className: "bg-success/10 text-success" },
  "Sortie": { label: "Sortie", className: "bg-warning/10 text-warning" },
  // Config
  Category: { label: "Catégorie", className: "bg-info/10 text-info" },
  Temperature: { label: "Température", className: "bg-info/10 text-info" },
  Weight: { label: "Poids", className: "bg-muted text-muted-foreground" },
  Custom: { label: "Custom", className: "bg-muted text-muted-foreground" },
  // Integration
  Connected: { label: "Connecté", className: "bg-success/10 text-success" },
  Disconnected: { label: "Déconnecté", className: "bg-muted text-muted-foreground" },
  Error: { label: "Erreur", className: "bg-destructive/10 text-destructive" },
  Syncing: { label: "Sync…", className: "bg-info/10 text-info" },
  ERP: { label: "ERP", className: "bg-primary/10 text-primary" },
  "E-Commerce": { label: "E-Commerce", className: "bg-info/10 text-info" },
  Carrier: { label: "Transporteur", className: "bg-warning/10 text-warning" },
  Accounting: { label: "Comptabilité", className: "bg-muted text-muted-foreground" },
  InApp: { label: "In-App", className: "bg-info/10 text-info" },
  Email: { label: "Email", className: "bg-warning/10 text-warning" },
  // Alert/Import
  StockLevel: { label: "Niveau stock", className: "bg-warning/10 text-warning" },
  ExpiryDate: { label: "Date exp.", className: "bg-destructive/10 text-destructive" },
  OrderDelay: { label: "Retard cmd", className: "bg-warning/10 text-warning" },
  CycleCountVariance: { label: "Variance", className: "bg-info/10 text-info" },
  Products: { label: "Produits", className: "bg-primary/10 text-primary" },
  Inventory: { label: "Inventaire", className: "bg-info/10 text-info" },
  Vendors: { label: "Fournisseurs", className: "bg-warning/10 text-warning" },
  Customers: { label: "Clients", className: "bg-info/10 text-info" },
  PurchaseOrders: { label: "Commandes", className: "bg-primary/10 text-primary" },
  Locations: { label: "Emplacements", className: "bg-muted text-muted-foreground" },
  Unblocked: { label: "Débloqué", className: "bg-success/10 text-success" },
  Processing: { label: "Traitement", className: "bg-info/10 text-info" },
  Quarantine: { label: "Quarantaine", className: "bg-destructive/10 text-destructive" },
  Expired: { label: "Expiré", className: "bg-destructive/10 text-destructive" },
  Recalled: { label: "Rappelé", className: "bg-destructive/10 text-destructive" },
  Consumed: { label: "Consommé", className: "bg-muted text-muted-foreground" },
  In_Stock: { label: "En stock", className: "bg-success/10 text-success" },
  Sold: { label: "Vendu", className: "bg-primary/10 text-primary" },
  Defective: { label: "Défectueux", className: "bg-destructive/10 text-destructive" },
  Scrapped: { label: "Mis au rebut", className: "bg-muted text-muted-foreground" },
  Below: { label: "En dessous", className: "bg-warning/10 text-warning" },
  Above: { label: "Au dessus", className: "bg-info/10 text-info" },
  Equals: { label: "Égal", className: "bg-muted text-muted-foreground" },
  Within: { label: "Dans", className: "bg-info/10 text-info" },
};

interface StatusBadgeProps {
  status: string;
  className?: string;
}

export default function StatusBadge({ status, className }: StatusBadgeProps) {
  const config = statusMap[status] || { label: status, className: "bg-muted text-muted-foreground" };
  return (
    <span className={cn("inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold", config.className, className)}>
      {config.label}
    </span>
  );
}
