
// Sample course data that links to centers
export const coursesData = [
  {
    id: 1,
    name: "Advanced Fitness Training",
    category: "Fitness & Health",
    rating: 4.9,
    reviews: 42,
    duration: "8 weeks",
    image:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    price: "$350",
    featured: true,
    description: "Comprehensive fitness program designed to help you reach your peak physical condition with professional trainers.",
    centerId: 1,
    centerName: "Elite Fitness Academy",
    centerLocation: "San Francisco, CA",
  },
  {
    id: 2,
    name: "Full-Stack Web Development",
    category: "Programming",
    rating: 4.8,
    reviews: 78,
    duration: "12 weeks",
    image:
      "https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    price: "$1,200",
    featured: true,
    description: "Learn front-end and back-end development skills to build complete web applications from scratch.",
    centerId: 2,
    centerName: "Tech Skills Institute",
    centerLocation: "Austin, TX",
  },
  {
    id: 3,
    name: "Spanish for Beginners",
    category: "Language Learning",
    rating: 4.7,
    reviews: 65,
    duration: "10 weeks",
    image:
      "https://images.unsplash.com/photo-1501504905252-473c47e087f8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1374&q=80",
    price: "$299",
    featured: false,
    description: "Start your language journey with our comprehensive Spanish course for complete beginners.",
    centerId: 3,
    centerName: "Global Language Center",
    centerLocation: "New York, NY",
  },
  {
    id: 4,
    name: "Leadership Mastery",
    category: "Professional Skills",
    rating: 4.9,
    reviews: 89,
    duration: "6 weeks",
    image:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    price: "$499",
    featured: true,
    description: "Develop essential leadership skills to advance your career and lead teams effectively.",
    centerId: 4,
    centerName: "Business Leadership Academy",
    centerLocation: "Chicago, IL",
  },
  {
    id: 5,
    name: "Digital Painting Fundamentals",
    category: "Arts & Design",
    rating: 4.6,
    reviews: 52,
    duration: "8 weeks",
    image:
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1480&q=80",
    price: "$275",
    featured: false,
    description: "Learn the foundations of digital painting including color theory, composition, and digital tools.",
    centerId: 5,
    centerName: "Creative Arts Studio",
    centerLocation: "Portland, OR",
  },
  {
    id: 6,
    name: "Gourmet Cooking Masterclass",
    category: "Cooking",
    rating: 4.8,
    reviews: 73,
    duration: "4 weeks",
    image:
      "https://images.unsplash.com/photo-1556910103-1c02745aae4d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    price: "$320",
    featured: true,
    description: "Master gourmet cooking techniques with professional chefs to create restaurant-quality dishes at home.",
    centerId: 6,
    centerName: "Culinary Institute",
    centerLocation: "Seattle, WA",
  },
];
