// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xwdykfrgexagoqfvmblw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3ZHlrZnJnZXhhZ29xZnZtYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTU4OTgsImV4cCI6MjA3NDM3MTg5OH0.JA601-YfTIpbx-yJCuHOl4XuJnPdbCl0o6DT9OdswRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});